import PrivateLayout from './layouts/PrivateLayout';
import PublicLayout from './layouts/PublicLayout';
import './global.css';

export const metadata = {
  title: 'Welcome to medium-web',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const res = await fetch('http://localhost:3000/api')
  const data = await res.json();
  const Layout = data.isAuthorized ? PrivateLayout :  PublicLayout;
  return (
    <html lang="en">
      <body>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
