import React from "react";

export const metadata = {
  title: 'Welcome to medium-web',
  description: 'Generated by create-nx-workspace',
};

export default function PrivateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <React.Fragment>
      {children}
    </React.Fragment>
  );
}
