import { Header, LoginModal } from '@medium/components';

export const metadata = {
  title: 'Welcome to medium-web',
  description: 'Generated by create-nx-workspace',
};

export default function PublicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="bb ah"></div>
        {children}
        <LoginModal />
      </body>
    </html>
  );
}
